build:
  environment:
    timezone: 'Europe/Berlin'
    php:
      version: '7.1'
      ini:
        'date.timezone': 'Europe/Berlin'
        'opcache.enable': '1'
        'opcache.enable_cli': '1'
        'zend.assertions': '1'
        'assert.exception': 'On'
  nodes:
    analysis:
      project_setup:
        override: true
      dependencies:
        override:
          - composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv
      tests:
        override:
          -
            command: php-scrutinizer-run --enable-security-analysis
            use_website_config: false
          -
            command: phpcs-run --colors --standard=phpcs.xml
            use_website_config: false
    tests:
      project_setup:
        override: true
      dependencies:
        override:
          - composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv
      tests:
        override:
          - command: vendor/bin/phpunit -c phpunit.xml --colors --columns 117 --no-coverage
    coverage:
      project_setup:
        override: true
      dependencies:
        override:
          - composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest -vv
      tests:
        override:
            - command: vendor/bin/phpunit -c phpunit.xml --colors --columns 117 --coverage-clover=clover.xml --coverage-text
              coverage:
                file: clover.xml   # <- Set this to where we find the coverage data.
                #    The path is relative to the current directory.
                format: clover
filter:
  excluded_paths:
    - 'tests/*'
  dependency_paths:
    - 'vendor/*'
checks:
  php: true
